### ISSUE TITLE
Support for d3.js v4?

### ISSUE THREAD

**Issue by Spone** [veltman/mapstarter#1]
Hello,
I'm wondering if you plan to support d3.js v4? I'm having trouble adapting the generated code to make it work, especially the zoom.
Thanks!

**Comment by veltman** [comment]
Eventually I'm going to rebuild this whole thing but I probably won't get around to upgrading to v4 separately from that... sorry!

**Comment by Spone** [comment]
Thanks for your reply and this very useful tool!
